# Generated by Django 3.2.9 on 2022-02-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_offer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.IntegerField()),
                ('acceptance_status', models.BooleanField(verbose_name='Kabul Durumu ')),
                ('read_status', models.BooleanField(verbose_name='okundu Durumu ')),
                ('ads_ofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads_data', verbose_name='Teklif Alan İlan ')),
                ('offer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İlan Teklifi Yapan ')),
            ],
        ),
    ]
