# Generated by Django 3.2.9 on 2022-03-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0019_company_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0004_auto_20220302_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='expert_expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.IntegerField(verbose_name='Teklif Edilen Miktar')),
                ('acceptance_status', models.BooleanField(verbose_name='Kabul Durumu ')),
                ('read_status', models.BooleanField(verbose_name='okundu Durumu ')),
                ('veto_status', models.BooleanField(null=True, verbose_name='Red Durumu')),
                ('offer_date', models.DateField(auto_now_add=True, null=True)),
                ('expert_offers_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teklif Alan Kullancıı ')),
                ('offer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.user_profil', verbose_name='Teklifi Yapan Kullanıcı')),
            ],
        ),
    ]
