# Generated by Django 3.2.9 on 2022-03-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20220305_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='teklif_redd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redd', models.CharField(max_length=150, verbose_name='Reddedilme Sebebi')),
                ('adds_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.ad_offer_user', verbose_name='Teklif Alan İlan ')),
            ],
        ),
    ]
