# Generated by Django 3.2.9 on 2022-03-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_category_ads_ilan_calima_saati'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0007_teklif_redd'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_offer_user_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.BooleanField(verbose_name='Kabul Durumu ')),
                ('read_status', models.BooleanField(verbose_name='okundu Durumu ')),
                ('veto_status', models.BooleanField(null=True, verbose_name='Red Durumu')),
                ('offer_date', models.DateField(auto_now_add=True, null=True)),
                ('ads_ofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads_data', verbose_name='Teklif Alan İlan ')),
                ('offer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İlan Teklifi Yapan ')),
            ],
        ),
    ]
