# Generated by Django 3.2.9 on 2022-02-17 08:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_basligi', models.CharField(max_length=50, verbose_name='İlan')),
                ('kisa_ilan_aciklamasi', models.CharField(max_length=250, verbose_name='Kısa İlan Açıklaması')),
                ('ilan', ckeditor.fields.RichTextField()),
                ('ilan_olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('İlan_gorseli', models.FileField(blank=True, null=True, upload_to='ilan_gorsel/', verbose_name='ilana Fotoğraf Ekleyin')),
                ('max_ucret', models.PositiveBigIntegerField(null=True, verbose_name='Maxsumum Ücret')),
                ('min_ucret', models.PositiveBigIntegerField(null=True, verbose_name='Minimum Ücret')),
                ('ilan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İlan Sahibi ')),
            ],
            options={
                'ordering': ['-ilan_olusturma_tarihi'],
            },
        ),
    ]
