# Generated by Django 3.2.9 on 2022-02-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0004_ucretlendirme'),
        ('ads', '0002_auto_20220228_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aranan_deneyim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_category.deneyim', verbose_name='İlan Deneyimi ')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads_data', verbose_name='İlan Sahibi ')),
                ('ilan_calima_saati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_category.calisma_saati', verbose_name='İlan Çalışma Saati ')),
                ('ilan_ucretlendirmesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_category.ucretlendirme', verbose_name='İlan Ücretlendirmesi')),
                ('lokasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_category.lokasyon', verbose_name='İlan Lokasyonu ')),
            ],
        ),
    ]
