# Generated by Django 3.2.9 on 2022-02-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0004_ucretlendirme'),
        ('ads', '0003_category_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_ads',
            name='aranan_deneyim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.deneyim', verbose_name='İlan Deneyimi '),
        ),
        migrations.AlterField(
            model_name='category_ads',
            name='ilan_calima_saati',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.calisma_saati', verbose_name='İlan Çalışma Saati '),
        ),
        migrations.AlterField(
            model_name='category_ads',
            name='lokasyon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.lokasyon', verbose_name='İlan Lokasyonu '),
        ),
    ]
