# Generated by Django 3.2.9 on 2022-03-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20220301_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads_data',
            name='max_ucret',
        ),
        migrations.RemoveField(
            model_name='ads_data',
            name='min_ucret',
        ),
    ]
