# Generated by Django 3.2.9 on 2022-03-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0005_deneyim_siralama_puani'),
        ('ads', '0006_ads_data_ilan_gecis_tablosu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_ads',
            name='ilan_calima_saati',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.kategoriler', verbose_name='İlan Çalışma Saati '),
        ),
    ]
