# Generated by Django 3.2.9 on 2022-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_category_ads_ilan_calima_saati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads_data',
            name='kisa_ilan_aciklamasi',
            field=models.TextField(max_length=250, verbose_name='Kısa İlan Açıklaması'),
        ),
    ]
