# Generated by Django 3.2.9 on 2022-02-21 07:09

import all_category.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', all_category.models.user_adi(max_length=200, null=True, verbose_name='Adı Soyadı')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='E-Posta')),
                ('telefon', models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('profil_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Görseli')),
                ('on_bilgi', models.TextField(null=True, verbose_name='Kartvizit Bilgisi')),
                ('minumum_ucret', models.IntegerField(null=True)),
                ('one_cikan_yetenek', models.CharField(max_length=200, null=True, verbose_name='Öne Çıkan Yetenek ')),
                ('kullanici_durumu', models.BooleanField(null=True, verbose_name='Şirket')),
                ('kullanici_tipi', models.CharField(max_length=1, null=True, verbose_name='Kullanıcı Paket Durumu ')),
                ('bakiye', models.IntegerField(null=True)),
                ('lokasyon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.lokasyon', verbose_name='Lokasyon Bilgisi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_kategori', models.ForeignKey(blank=True, help_text='Kullanıcı Biligi Kategorisi', null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.kategoriler')),
            ],
        ),
    ]
