# Generated by Django 3.2.9 on 2022-02-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profil',
            name='kullanici_durumu',
        ),
    ]
