# Generated by Django 3.2.9 on 2022-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_remove_user_profil_kullanici_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Arkaplan Görseli'),
        ),
    ]
