# Generated by Django 3.2.9 on 2022-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_user_profil_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=40, verbose_name='Başlık')),
                ('aciklama', models.TextField(max_length=150, verbose_name='Açıklama')),
                ('tarih', models.DateField(verbose_name='Tarih')),
            ],
        ),
    ]
