# Generated by Django 3.2.9 on 2022-02-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0002_calisma_saati_deneyim_ekip_durumu_is_beklentisi_programlama_dili'),
        ('profil', '0006_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='deneyim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.deneyim', verbose_name='Lokasyon Bilgisi'),
        ),
    ]
