# Generated by Django 3.2.9 on 2022-02-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0002_calisma_saati_deneyim_ekip_durumu_is_beklentisi_programlama_dili'),
        ('profil', '0007_user_profil_deneyim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profil',
            name='one_cikan_yetenek',
        ),
        migrations.AddField(
            model_name='user_profil',
            name='calisma_saat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.calisma_saati', verbose_name='Lokasyon Bilgisi'),
        ),
    ]
