# Generated by Django 3.2.9 on 2022-02-22 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_category', '0002_calisma_saati_deneyim_ekip_durumu_is_beklentisi_programlama_dili'),
        ('profil', '0008_auto_20220222_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='working_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.calisma_saati', verbose_name='İş Çalışma Saati')),
                ('is_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.is_beklentisi', verbose_name='İş Beklentisi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Bilgisi')),
            ],
        ),
    ]
