# Generated by Django 3.2.9 on 2022-02-22 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_category', '0002_calisma_saati_deneyim_ekip_durumu_is_beklentisi_programlama_dili'),
        ('profil', '0010_alter_working_condition_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deneyimler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.deneyim', verbose_name='Deneyim Bilgisi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Bilgisi')),
                ('yetenek_dil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.programlama_dili', verbose_name='Yetenek Bilgisi')),
            ],
        ),
    ]
