# Generated by Django 3.2.9 on 2022-02-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0003_current_situation'),
        ('profil', '0011_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_condition',
            name='calisma_durumu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.current_situation', verbose_name='Çalışma Durumu'),
        ),
    ]
