# Generated by Django 3.2.9 on 2022-02-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0003_current_situation'),
        ('profil', '0012_working_condition_calisma_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_condition',
            name='deneyim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.deneyim', verbose_name='Deneyim'),
        ),
    ]
