# Generated by Django 3.2.9 on 2022-02-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_working_condition_deneyim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profil',
            name='calisma_saat',
        ),
        migrations.RemoveField(
            model_name='user_profil',
            name='deneyim',
        ),
    ]
