# Generated by Django 3.2.9 on 2022-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_auto_20220223_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
