# Generated by Django 3.2.9 on 2022-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0017_auto_20220223_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='yon',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
