# Generated by Django 3.2.9 on 2022-02-24 20:40

import all_category.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_category', '0003_current_situation'),
        ('profil', '0018_resume_yon'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', all_category.models.user_adi(max_length=200, null=True, verbose_name='Şirket Adı')),
                ('company_email', models.EmailField(max_length=200, null=True, verbose_name='E-Posta')),
                ('company_telefon', models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('profil_img', models.FileField(blank=True, null=True, upload_to='profil/', verbose_name='Profil Görseli')),
                ('background', models.FileField(blank=True, null=True, upload_to='back/', verbose_name='Arkaplan Görseli')),
                ('company_explanation', models.TextField(null=True, verbose_name='Şirket Açıklaması')),
                ('lokasyon', models.TextField(null=True, verbose_name='Şirket Lokasyon')),
                ('company_foundation_year', models.DateField(auto_now_add=True, null=True)),
                ('kullanici_tipi', models.CharField(max_length=1, null=True, verbose_name='Kullanıcı Paket Durumu ')),
                ('bakiye', models.IntegerField(null=True)),
                ('create_at', models.DateField(auto_now_add=True, null=True)),
                ('company_about', ckeditor.fields.RichTextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_kategori', models.ForeignKey(blank=True, help_text='Kullanıcı Biligi Kategorisi', null=True, on_delete=django.db.models.deletion.CASCADE, to='all_category.kategoriler')),
            ],
        ),
    ]
