# Generated by Django 3.2.9 on 2022-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0022_degerlendirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='degerlendirme_puanli',
            field=models.IntegerField(null=True),
        ),
    ]
