# Generated by Django 3.2.9 on 2022-03-10 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0023_user_profil_degerlendirme_puanli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degerlendirme',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.user_profil', verbose_name='Oy Alan'),
        ),
    ]
