# Generated by Django 3.2.9 on 2022-03-21 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_category_ads_ilan_calima_saati'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0026_mail_dogrulama_tel_dogrulama'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_offers_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip ')),
                ('offer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.user_profil', verbose_name='favori user')),
            ],
        ),
        migrations.CreateModel(
            name='fav_adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_ofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads_data', verbose_name='Teklif Alan İlan ')),
                ('expert_offers_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahip ')),
            ],
        ),
    ]
