# Generated by Django 3.2.9 on 2022-03-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0028_user_profil_user_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profil',
            old_name='user_about',
            new_name='company_about',
        ),
    ]
