# Generated by Django 3.2.9 on 2022-02-18 12:41

import all_category.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lokasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir_ismi', all_category.models.sehir_duzeltme(max_length=100, verbose_name='Şehir İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategory_ismi', all_category.models.user_adi(max_length=100, verbose_name='Kategori İsmi')),
                ('link', all_category.models.kategory_link_ayari(max_length=200)),
                ('keywords', models.CharField(max_length=255)),
                ('ust_kategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='all_category.kategoriler')),
            ],
        ),
    ]
