# Generated by Django 3.2.9 on 2022-02-21 09:02

import all_category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisma_saati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_saat', models.CharField(max_length=100, verbose_name='Haftalık çalışma saati')),
            ],
        ),
        migrations.CreateModel(
            name='deneyim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecrube', models.CharField(max_length=20, verbose_name='Tecrübeler')),
            ],
        ),
        migrations.CreateModel(
            name='ekip_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekip', models.CharField(max_length=100, verbose_name='Ekip Durumu')),
            ],
        ),
        migrations.CreateModel(
            name='is_beklentisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_beklentisi', models.CharField(max_length=100, verbose_name='İş Beklentisi')),
            ],
        ),
        migrations.CreateModel(
            name='programlama_dili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dil', all_category.models.sehir_duzeltme(max_length=100, verbose_name='Yetenek')),
            ],
        ),
    ]
