# Generated by Django 3.2.9 on 2022-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0002_calisma_saati_deneyim_ekip_durumu_is_beklentisi_programlama_dili'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calisma_durumu', models.CharField(max_length=100, verbose_name='Çalışma Durumu')),
            ],
        ),
    ]
