# Generated by Django 3.2.9 on 2022-02-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_category', '0003_current_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ucretlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucretlendirmesi', models.CharField(max_length=100, verbose_name='İş ücretlenmesi')),
            ],
        ),
    ]
