# Generated by Django 3.2.9 on 2022-03-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operations', '0002_user_status_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Durumu'),
        ),
    ]
