# Generated by Django 3.2.9 on 2022-03-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads_data',
            new_name='paketler',
        ),
    ]
