# Generated by Django 3.2.9 on 2022-03-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0002_rename_ads_data_paketler'),
    ]

    operations = [
        migrations.CreateModel(
            name='odemeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payment_much', models.IntegerField()),
                ('user_payment_date', models.DateField(auto_now_add=True, null=True)),
                ('user_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paket Satın Alan')),
            ],
        ),
    ]
